version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests...
      - npm test
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**/*